### PR TITLE
Autoinstall through https://github.com/phpstan/extension-installer

### PR DESCRIPTION
**Pull request by spawnia**

### CODE REVIEW

**Comment by szepeviktor** [comment]
What a modernization!

**Comment by szepeviktor** [comment]
Try running `composer global require localheinz/composer-normalize`

**Comment by szepeviktor** [comment]
- localheinz/composer-normalize is not a dev dependency, it needs to be installed globally
- GitHub's syntax highlight does not understand "neon", [only "yaml" ](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L5864)

**Comment by bmaziere** [comment]
thx @spawnia for contributing. agreed with @szepeviktor on the 2 points. I would add don't forget to update Changelog and if you can squash your commit that would be great. thx again for this modernization 😄

**Comment by spawnia** [comment]
I would argue it is a dev dependency, as dev's are expected to run it and it is useful to validate in CI. There is no hard requirement that forces it to be installed globally.

**Comment by spawnia** [comment]
You can squash on merge, the title of the PR should make a good commit message.

**Comment by mremi** [comment]
Thanks @spawnia for the contribution!

About commits, of course we can squash them on merge, but it's easier for the merger if the submitted PR is "clean", because no need talking about that, and the author gets the opportunity to update the commit message to have a proper one.

**Pull request merged**
