### PR TITLE
 Allow installation with PHP 8.0

### PR DESCRIPTION
**Pull request by nauxliu**

### CODE REVIEW

**Comment by mremi** [comment]
Hi, thanks for contributing, could you please update the Travis config as well?

**Comment by nauxliu** [comment]
Looks like Travis does not support PHP 8.0, we might need to migrate Travis to GitHub Actions due to travis-ci.org will be shutting down in several weeks

**Comment by nauxliu** [comment]
Ready for review

**Review by nepda — DISMISSED** [review]
There are two things happening here. Change of `composer.json` to be able to run with PHP 8.0.

And the other thing is switching from Travis to GitHub. Both okay as far as I understand.

**Comment by nepda** [comment]
PHP 8.0 is now supported by Travis. If it is not wanted to switch to GitHub workflows. But as mentioned, one need to switch from travis-ci.org to travis-ci.com in the near future.

**Comment by nauxliu** [comment]
I've moved the Travis to actions change to a separate PR #40, Can get this PR merged? this is the only package that blocks us from upgrading to 8.0

**Review by nepda — APPROVED** [review]

**Comment by mremi** [comment]
@nauxliu Hi, thanks for contributing, the build for PHP 8 is failing because of the dist version, could you please update it to `xenial`?

**Comment by Jurigag** [comment]
PHP Cs fixer is not supported for PHP8 yet, could you disable it for this workflow?

**Comment by mremi** [comment]
Thanks!

**Comment by nauxliu** [comment]
Hi @mremi , Could you cut a new release for this change?

**Comment by mremi** [comment]
Hi all, sorry for the delay but here we are https://github.com/ekino/phpstan-banned-code/releases/tag/v0.4.0

**Pull request merged**
